apiVersion: v1
kind: Service
metadata:
  labels:
    app: exchange-service
  name: exchange-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
1    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: exchange-service