apiVersion: v1
kind: Service
metadata:
  labels:
    app: exchange-service
  name: exchange-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30327
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: exchange-service
  sessionAffinity: None
  type: LoadBalancer