apiVersion: v1
kind: Service
metadata:
  labels:
    app: exchange-service
  name: exchange-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 8100
      targetPort: 8100
      protocol: TCP
  selector:
    app: exchange-service